name: Deploy Payment Service

on:
  push:
    branches: [main]
    paths:
      - "services/payment-service/**"
      - ".github/workflows/deploy-payment-service.yml"
      - ".github/workflows/deploy-service.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: payment-service
      task_definition: payment_service
      container_name: payment-service
