name: Deploy Order Service

on:
  push:
    branches: [main]
    paths:
      - "services/order-service/**"
      - ".github/workflows/deploy-order-service.yml"
      - ".github/workflows/deploy-service.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: order-service
      task_definition: order_service
      container_name: order-service
